version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontalumnos:
      container_name: frontalumnos
      build:
        context: ./frontalumnos
      ports:
        - "5173:5173"
      environment:
        - CHOKIDAR_USEPOLLING=true
      
volumes:
  pgdata: {}